# Generated by Django 5.0.4 on 2024-06-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='docanexoactividad',
            field=models.FileField(blank=True, db_column='DOCANEXOACTIVIDAD', null=True, upload_to='uploads/'),
        ),
    ]
