# Generated by Django 5.0.4 on 2024-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('idtipoCliente', models.AutoField(db_column='IDCLIENTE', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=255)),
            ],
            options={
                'db_table': 'tipocliente',
                'managed': True,
            },
        ),
    ]
