# Generated by Django 5.0.4 on 2024-10-24 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='iddepartamento',
            field=models.ForeignKey(blank=True, db_column='IDDEPARTAMENTO', null=True, on_delete=django.db.models.deletion.CASCADE, to='SIGEA_APP.departamentos'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='IDUSUARIO', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
