# Generated by Django 5.0.4 on 2024-06-16 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='invitadosactividad',
        ),
        migrations.CreateModel(
            name='invitados_actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idactividad', models.ForeignKey(db_column='IDACTIVIDAD', on_delete=django.db.models.deletion.DO_NOTHING, to='SIGEA_APP.actividades')),
                ('idusuario', models.ForeignKey(db_column='IDUSUARIO', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitados_actividad',
                'managed': True,
                'unique_together': {('idactividad', 'idusuario')},
            },
        ),
    ]
