# Generated by Django 5.0.4 on 2024-11-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='idCliente',
            field=models.ForeignKey(db_column='IDCLIENTE', on_delete=django.db.models.deletion.CASCADE, to='SIGEA_APP.cliente'),
        ),
    ]
