# Generated by Django 5.0.4 on 2024-06-12 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idtipousuario', models.AutoField(db_column='IDTIPOUSUARIO', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=255)),
            ],
            options={
                'db_table': 'tipousuario',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipousuario',
            field=models.ForeignKey(db_column='IDTIPOUSUARIO', on_delete=django.db.models.deletion.DO_NOTHING, to='SIGEA_APP.tipousuario'),
        ),
    ]
