# Generated by Django 5.0.4 on 2024-07-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0002_alter_usuario_dui_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(db_column='TELEFONO', max_length=9, unique=True),
        ),
    ]
