# Generated by Django 5.0.4 on 2024-07-24 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0002_tipocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('correo', models.CharField(db_column='CORREO', max_length=100)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=9, unique=True)),
                ('idTipo', models.ForeignKey(db_column='IDTIPOCLIENTE', on_delete=django.db.models.deletion.CASCADE, to='SIGEA_APP.tipocliente')),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
    ]
