# Generated by Django 5.0.4 on 2024-10-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0002_evaluacion_iddepartamento_alter_evaluacion_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='evaluaciones',
            field=models.ManyToManyField(blank=True, related_name='departamento_evaluaciones', to='SIGEA_APP.evaluacion'),
        ),
    ]
