# Generated by Django 5.0.4 on 2024-10-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0003_departamentos_evaluaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='evaluaciones',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='iddepartamento',
        ),
    ]
