# Generated by Django 5.0.4 on 2024-06-15 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0003_auto_20240612_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandesarrollo',
            name='amenazas',
            field=models.TextField(blank=True, db_column='AMENAZAS', null=True),
        ),
        migrations.AddField(
            model_name='plandesarrollo',
            name='debilidades',
            field=models.TextField(blank=True, db_column='DEBILIDADES', null=True),
        ),
        migrations.AddField(
            model_name='plandesarrollo',
            name='fortalezas',
            field=models.TextField(blank=True, db_column='FORTALEZAS', null=True),
        ),
        migrations.AddField(
            model_name='plandesarrollo',
            name='oportunidades',
            field=models.TextField(blank=True, db_column='OPORTUNIDADES', null=True),
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='invitadosactividad',
        ),
        migrations.AddField(
            model_name='actividades',
            name='invitadosactividad',
            field=models.ManyToManyField(related_name='actividades_invitado', to=settings.AUTH_USER_MODEL),
        ),
    ]
