# Generated by Django 5.0.4 on 2024-07-30 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0004_alter_invitados_actividad_idactividad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoActividad',
            fields=[
                ('idestado', models.AutoField(db_column='IDESTADO', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=255)),
            ],
            options={
                'db_table': 'estadoactividad',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='actividades',
            name='estadoactividad',
            field=models.ForeignKey(db_column='IDESTADO', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='SIGEA_APP.estadoactividad'),
        ),
    ]
