# Generated by Django 5.0.4 on 2024-08-26 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0003_cliente'),
        ('SIGEA_APP', '0005_estadoactividad_actividades_estadoactividad'),
    ]

    operations = [
    ]
