# Generated by Django 5.0.4 on 2024-06-16 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0005_remove_plandesarrollo_idusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='responsabledepartamento',
            field=models.ForeignKey(blank=True, db_column='RESPONSABLEDEPARTAMENTO', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='idplandes',
            field=models.ForeignKey(blank=True, db_column='IDPLANDES', null=True, on_delete=django.db.models.deletion.CASCADE, to='SIGEA_APP.plandesarrollo'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='idusuario',
            field=models.ForeignKey(db_column='IDUSUARIO', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plandesarrollo',
            name='idevaluacion',
            field=models.ForeignKey(db_column='IDEVALUACION', on_delete=django.db.models.deletion.CASCADE, to='SIGEA_APP.evaluacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dui',
            field=models.CharField(db_column='DUI', max_length=9, unique=True),
        ),
    ]
