# Generated by Django 5.0.4 on 2024-08-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0007_licencia_registroasistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
