# Generated by Django 5.0.4 on 2024-08-29 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0008_alter_registroasistencia_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='empleado',
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='horas_trabajadas',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddConstraint(
            model_name='registroasistencia',
            constraint=models.CheckConstraint(check=models.Q(('hora_salida__gte', models.F('hora_entrada'))), name='check_hora_entrada_salida'),
        ),
        migrations.AlterModelTable(
            name='registroasistencia',
            table='registro_asistencia',
        ),
        migrations.DeleteModel(
            name='Licencia',
        ),
    ]
