# Generated by Django 5.0.4 on 2024-08-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0009_remove_licencia_empleado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroasistencia',
            old_name='id',
            new_name='idregistro',
        ),
    ]
