# Generated by Django 5.0.4 on 2024-08-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0010_rename_id_registroasistencia_idregistro'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registroasistencia',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha'), name='unique_registro_asistencia'),
        ),
    ]
