# Generated by Django 5.0.4 on 2024-08-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0011_registroasistencia_unique_registro_asistencia'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registroasistencia',
            name='unique_registro_asistencia',
        ),
        migrations.AddConstraint(
            model_name='registroasistencia',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha'), name='unique_empleado_fecha'),
        ),
    ]
