# Generated by Django 5.0.4 on 2024-10-23 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0012_remove_registroasistencia_unique_registro_asistencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='idplandes',
            field=models.ForeignKey(blank=True, db_column='IDPLANDES', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SIGEA_APP.plandesarrollo'),
        ),
        migrations.AlterField(
            model_name='plandesarrollo',
            name='idevaluacion',
            field=models.ForeignKey(db_column='IDEVALUACION', on_delete=django.db.models.deletion.DO_NOTHING, to='SIGEA_APP.evaluacion'),
        ),
    ]
