# Generated by Django 5.0.4 on 2024-10-23 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0013_alter_evaluacion_idplandes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='idplandes',
            field=models.ForeignKey(blank=True, db_column='IDPLANDES', null=True, on_delete=django.db.models.deletion.CASCADE, to='SIGEA_APP.plandesarrollo'),
        ),
    ]
