# Generated by Django 5.0.4 on 2024-10-23 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEA_APP', '0014_alter_evaluacion_idplandes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandesarrollo',
            name='idevaluacion',
            field=models.ForeignKey(db_column='IDEVALUACION', on_delete=django.db.models.deletion.CASCADE, to='SIGEA_APP.evaluacion'),
        ),
    ]
